language: java
jdk:
- oraclejdk8
services:
- mysql
before_install:
- mysql -e 'drop database if exists testspongeblog;'
- mysql -e 'create database testspongeblog;'
- mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');"
script:
- mvn test -B
