# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
server:
  port: ${APP_PORT:8081}
# Connection url for the database "netgloo_blog"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spongeblog?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
# Username and password
    username: root
    password: root
# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
# Show or not log for each sql query
  jpa: 
    database: mysql
#    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: validate
  jackson: 
    date-format: com.flockinger.spongeblogSP.config.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  http:
#    multipart:
#      max-file-size: 5300KB
#      max-request-size: 5300KB

### config for getting Hibernate generated SQL
#      ddl-auto: create-drop
#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: DEBUG
#        SQL: DEBUG   
#        type: TRACE  
###

flyway:
  baseline-on-migrate: true


#logging:
#  level:
#    org.springframework.security: DEBUG      
    
blog:
  paging:
    default-page: 0
    default-items-per-page: 5
  preview-text-size: 50

## simple service-to-service security
security-admin:
  clientid: ${SEC_CLIENT_ID:spongeblog-admin}
  secretkey: ${SEC_CLIENT_ID:p0F0J5y1Yk5bSPvJqfa8YThfKNnunQUC}
security-author:
  clientid: ${SEC_CLIENT_ID:spongeblog-user}
  secretkey: ${SEC_CLIENT_ID:DqvRMa9RUtkLi9W6CQaZyuPY3kk1AzVK}
      
#### Test Profile
---
spring: 
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/testspongeblog?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
flyway:
  baseline-on-migrate: true

blog:
  preview-text-size: 7


#### Production Profile
---
spring: 
  profiles: production
  
blog:
  paging:
    default-page: 0
    default-items-per-page: 5
  preview-text-size: 50
  
    