# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection
server:
  port: ${APP_PORT:8081}
# Connection url for the database "netgloo_blog"
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/spongeblog?useSSL=false&useUnicode=yes&characterEncoding=UTF-8}
# Username and password
    username: ${DB_USER:root}
    password: ${DB_PASSWORD:root}
# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
# Show or not log for each sql query
  jpa: 
    database: mysql
    show-sql: ${SQL_QUERY_LOG:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: validate
  jackson: 
    date-format: com.flockinger.spongeblogSP.config.swagger.RFC3339DateFormat
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
#  http:
#    multipart:
#      max-file-size: 5300KB
#      max-request-size: 5300KB

### config for getting Hibernate generated SQL
#      ddl-auto: create-drop
#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: DEBUG
#        SQL: DEBUG   
#        type: TRACE  
###

flyway:
  baseline-on-migrate: ${FLYWAY_MIGRATE:true}


#logging:
#  level:
#    org.springframework.security: DEBUG      
    
blog:
  paging:
    default-page: ${BLOG_DEFAULT_PAGE:0}
    default-items-per-page: ${BLOG_DEFAULT_ITEMS_PER_PAGE:5}
  preview-text-size: ${BLOG_PREVIEW_TEXT_SIZE:50}
  security:
    allowed-origin: ${ALLOWED_CORS_ORIGIN:http://localhost:4200}

  
google:
  client:
    clientId: ${OAUTH_CLIENT_ID:dontcommittherealclientidagain}
    clientSecret: ${OAUTH_CLIENT_SECRET:dontcommittherealsecretagain}
    accessTokenUri: ${OAUTH_CLIENT_TOKEN_URI:https://www.googleapis.com/oauth2/v3/token}
    userAuthorizationUri: ${OAUTH_CLIENT_AUTH_URI:https://accounts.google.com/o/oauth2/auth}
  finalTargetUrl: ${OAUTH_CLIENT_REDIRECT_URL:http://localhost:4200/admin/login}
  verificationUrl: ${OAUTH_CLIENT_VERIFICATION_URL:https://www.googleapis.com/oauth2/v3/tokeninfo?id_token=}

security:
  basic:
    enabled: ${SECURITY_ENABLED:true}
      
#### Test Profile
---
spring: 
  profiles: test
  datasource:
    url: jdbc:mysql://localhost:3306/testspongeblog?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
flyway:
  baseline-on-migrate: true

blog:
  preview-text-size: 7
