# ===============================
# = DATA SOURCE
# ===============================

# Set here configurations for the database connection

# Connection url for the database "netgloo_blog"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spongeblog?useSSL=false&useUnicode=yes&characterEncoding=UTF-8
# Username and password
    username: root
    password: root
# Keep the connection alive if idle for a long time (needed in production)
    testWhileIdle: true
    validationQuery: SELECT 1
# Show or not log for each sql query
  jpa: 
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
# Hibernate ddl auto (create, create-drop, update): with "update" the database
# schema will be automatically updated accordingly to java entities found in
# the project
    hibernate:
      ddl-auto: validate
      
### config for getting Hibernate generated SQL
#      ddl-auto: create-drop
#logging:
#  level:
#    org:
#      hibernate:
#        tool:
#          hbm2ddl: DEBUG
#        SQL: DEBUG   
#        type: TRACE  
###

flyway:
  baseline-on-migrate: true